/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.factory;
import java.sql.*;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class cwh extends javax.swing.JFrame {

    /**
     * Creates new form cwh
     */
    
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    
    public cwh() {
        initComponents();
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            //JOptionPane.showMessageDialog(null,"Driver Loader");
            try{
                con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL","scott","tiger");
                //JOptionPane.showMessageDialog(null, "Connected to Database");
            }
            catch(SQLException ex){
                Logger.getLogger(cwh.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
        catch(ClassNotFoundException ex){
                Logger.getLogger(cwh.class.getName()).log(Level.SEVERE,null,ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_t = new javax.swing.JTextField();
        loc_t = new javax.swing.JTextField();
        cap_t = new javax.swing.JTextField();
        f_id_t = new javax.swing.JTextField();
        insert_b = new javax.swing.JButton();
        update_b = new javax.swing.JButton();
        delete_b = new javax.swing.JButton();
        search_b = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Central WareHouse Details");

        jLabel2.setText("CWD ID");

        jLabel3.setText("CHW Location");

        jLabel4.setText("CWH Capacity");

        jLabel5.setText("Factory ID");

        insert_b.setText("Insert");
        insert_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_bActionPerformed(evt);
            }
        });

        update_b.setText("Update");
        update_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bActionPerformed(evt);
            }
        });

        delete_b.setText("Detele");
        delete_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bActionPerformed(evt);
            }
        });

        search_b.setText("Search");
        search_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(insert_b)
                .addGap(18, 18, 18)
                .addComponent(update_b)
                .addGap(18, 18, 18)
                .addComponent(delete_b)
                .addGap(18, 18, 18)
                .addComponent(search_b)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loc_t, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_t, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cap_t, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_id_t, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loc_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cap_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f_id_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_b)
                    .addComponent(insert_b)
                    .addComponent(search_b)
                    .addComponent(delete_b))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_bActionPerformed
        String sql="insert into cwh(cwh_id,cwh_loaction,cwh_capacity,f_id) values(?,?,?,?)";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            ps.setString(2, loc_t.getText());
            ps.setInt(3, Integer.parseInt(cap_t.getText()));
            ps.setString(4, f_id_t.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted!");
        }
        catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't Insert!");
                Logger.getLogger(fac.class.getName()).log(Level.SEVERE,null,ex);
            }
    }//GEN-LAST:event_insert_bActionPerformed

    private void update_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bActionPerformed
       String sql="update cwh set cwh_loaction=?, cwh_capacity=?, f_id=? WHERE cwh_id=?";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, loc_t.getText());
            ps.setInt(2, Integer.parseInt(cap_t.getText()));
            ps.setString(3, f_id_t.getText());
            ps.setString(4, id_t.getText());
            int rowsUpdated=ps.executeUpdate();
            if(rowsUpdated>0){
                JOptionPane.showMessageDialog(null, "Updated successfully!");
            } 
            else{
                JOptionPane.showMessageDialog(null, "No record found with the given ID.");
            }
        } 
        catch(SQLException ex){
            Logger.getLogger(fac.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Can't Update!");
        }
    }//GEN-LAST:event_update_bActionPerformed

    private void delete_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bActionPerformed
        String sql = "delete cwh where cwh_id=?";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            int rowsDeleted=ps.executeUpdate();
            if(rowsDeleted>0){
                JOptionPane.showMessageDialog(null, "Deleted successfully!");
            } 
            else{
                JOptionPane.showMessageDialog(null, "No record found with the given ID.");
            }
        } 
        catch(SQLException ex){
            Logger.getLogger(fac.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Can't Delete!");
        }
    }//GEN-LAST:event_delete_bActionPerformed

    private void search_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bActionPerformed
        String sql="select * from cwh where cwh_id = ?";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            rs=ps.executeQuery();

            if(rs.next()){
                loc_t.setText(rs.getString("cwh_loaction"));
                cap_t.setText(rs.getString("cwh_capacity"));
                f_id_t.setText(rs.getString("f_id"));
                JOptionPane.showMessageDialog(null, "Record Found");
            } 
            else{
                JOptionPane.showMessageDialog(null, "No record found with the given ID");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(fac.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_search_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cwh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cwh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cwh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cwh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cwh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cap_t;
    private javax.swing.JButton delete_b;
    private javax.swing.JTextField f_id_t;
    private javax.swing.JTextField id_t;
    private javax.swing.JButton insert_b;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField loc_t;
    private javax.swing.JButton search_b;
    private javax.swing.JButton update_b;
    // End of variables declaration//GEN-END:variables
}
