/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.factory;
import java.sql.*;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class fac extends javax.swing.JFrame {

    /**
     * Creates new form fac
     */
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    
    public fac() {
        initComponents();
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            JOptionPane.showMessageDialog(null,"Driver Loader");
            try{
                con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL","scott","tiger");
                JOptionPane.showMessageDialog(null, "Connected to Database");
            }
            catch(SQLException ex){
                Logger.getLogger(fac.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
        catch(ClassNotFoundException ex){
                Logger.getLogger(fac.class.getName()).log(Level.SEVERE,null,ex);
        }    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_t = new javax.swing.JTextField();
        name_t = new javax.swing.JTextField();
        capacity_t = new javax.swing.JTextField();
        emp_t = new javax.swing.JTextField();
        mc_id_t = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        insert_b = new javax.swing.JButton();
        update_b = new javax.swing.JButton();
        delete_b = new javax.swing.JButton();
        search_b = new javax.swing.JButton();
        cwh_b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Factory ID");

        jLabel2.setText(" Factory Name");

        jLabel3.setText("Capacity");

        jLabel4.setText("No.of Employees");

        jLabel5.setText("Medical Compamy ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Factory Details");

        insert_b.setText("Insert");
        insert_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_bActionPerformed(evt);
            }
        });

        update_b.setText("Update");
        update_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bActionPerformed(evt);
            }
        });

        delete_b.setText("Delete");
        delete_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bActionPerformed(evt);
            }
        });

        search_b.setText("Search");
        search_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bActionPerformed(evt);
            }
        });

        cwh_b.setText("Add CWH Details");
        cwh_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwh_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_t, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_t, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacity_t, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_t, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mc_id_t, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(insert_b)
                        .addGap(18, 18, 18)
                        .addComponent(update_b)
                        .addGap(18, 18, 18)
                        .addComponent(delete_b))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(cwh_b, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(search_b)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(capacity_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emp_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mc_id_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_b)
                    .addComponent(update_b)
                    .addComponent(delete_b)
                    .addComponent(search_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cwh_b)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_bActionPerformed
        String sql="insert into fac(f_id,f_name,f_capacity,f_emp,mc_id) values(?,?,?,?,?)";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            ps.setString(2, name_t.getText());
            ps.setInt(3, Integer.parseInt(capacity_t.getText()));
            ps.setInt(4, Integer.parseInt(emp_t.getText()));
            ps.setString(5, mc_id_t.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted!");
        }
        catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Can't Insert!");
                Logger.getLogger(fac.class.getName()).log(Level.SEVERE,null,ex);
            }
    }//GEN-LAST:event_insert_bActionPerformed

    private void update_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bActionPerformed
        String sql="update fac set f_name=?, f_capacity=?, f_emp=?, mc_id=? WHERE f_id=?";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, name_t.getText());
            ps.setInt(2, Integer.parseInt(capacity_t.getText()));
            ps.setInt(3, Integer.parseInt(emp_t.getText()));
            ps.setString(4, mc_id_t.getText());
            ps.setString(5, id_t.getText());
            int rowsUpdated=ps.executeUpdate();
            if(rowsUpdated>0){
                JOptionPane.showMessageDialog(null, "Updated successfully!");
            } 
            else{
                JOptionPane.showMessageDialog(null, "No record found with the given ID.");
            }
        } 
        catch(SQLException ex){
            Logger.getLogger(fac.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Can't Update!");
        }
    }//GEN-LAST:event_update_bActionPerformed

    private void delete_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bActionPerformed
        String sql = "delete fac where f_id=?";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            int rowsDeleted=ps.executeUpdate();
            if(rowsDeleted>0){
                JOptionPane.showMessageDialog(null, "Deleted successfully!");
            } 
            else{
                JOptionPane.showMessageDialog(null, "No record found with the given ID.");
            }
        } 
        catch(SQLException ex){
            Logger.getLogger(fac.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Can't Delete!");
        }
    }//GEN-LAST:event_delete_bActionPerformed

    private void search_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bActionPerformed
        String sql="select * from fac where f_id = ?";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            rs=ps.executeQuery();

            if(rs.next()){
                name_t.setText(rs.getString("f_name"));
                capacity_t.setText(rs.getString("f_capacity"));
                emp_t.setText(rs.getString("f_emp"));
                mc_id_t.setText(rs.getString("mc_id"));
                JOptionPane.showMessageDialog(null, "Record Found");
            } 
            else{
                JOptionPane.showMessageDialog(null, "No record found with the given ID");
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(fac.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_search_bActionPerformed

    private void cwh_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwh_bActionPerformed
        cwh cwh_b = new cwh();
        cwh_b.setVisible(true);
    }//GEN-LAST:event_cwh_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacity_t;
    private javax.swing.JButton cwh_b;
    private javax.swing.JButton delete_b;
    private javax.swing.JTextField emp_t;
    private javax.swing.JTextField id_t;
    private javax.swing.JButton insert_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mc_id_t;
    private javax.swing.JTextField name_t;
    private javax.swing.JButton search_b;
    private javax.swing.JButton update_b;
    // End of variables declaration//GEN-END:variables
}
