/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.factory;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * @author Asus
 */
public class mc extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form mc
     */
    public mc() {
        initComponents();
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            //JOptionPane.showMessageDialog(null,"Driver Loaded");
            try{
                con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL","scott","tiger");
                //JOptionPane.showMessageDialog(null, "Connected to Database");
            }
            catch(SQLException ex){
                Logger.getLogger(mc.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
        catch(ClassNotFoundException ex){
                Logger.getLogger(mc.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_t = new javax.swing.JTextField();
        location_t = new javax.swing.JTextField();
        insert_b = new javax.swing.JButton();
        update_b = new javax.swing.JButton();
        delete_b = new javax.swing.JButton();
        search_b = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fac_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_t = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insert_b.setText("insert");
        insert_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_bActionPerformed(evt);
            }
        });

        update_b.setText("update");
        update_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bActionPerformed(evt);
            }
        });

        delete_b.setText("delete");
        delete_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bActionPerformed(evt);
            }
        });

        search_b.setText("search");
        search_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Medical Company Details");

        fac_b.setText("Add Factory Details Click here!");
        fac_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_bActionPerformed(evt);
            }
        });

        jLabel1.setText("mc__id");

        jLabel2.setText("mc_name");

        jLabel3.setText("location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_t, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(name_t)
                            .addComponent(location_t)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4)
                        .addGap(123, 123, 123)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(insert_b)
                        .addGap(18, 18, 18)
                        .addComponent(update_b)
                        .addGap(18, 18, 18)
                        .addComponent(delete_b)
                        .addGap(18, 18, 18)
                        .addComponent(search_b))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(fac_b, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(location_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_b)
                    .addComponent(update_b)
                    .addComponent(delete_b)
                    .addComponent(search_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(fac_b)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_bActionPerformed
        String sql="insert into mc(mc_id,mc_name,location) values(?,?,?)";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1,id_t.getText());
            ps.setString(2,name_t.getText());
            ps.setString(3,location_t.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted !");
        }
        catch(SQLException ex){
            Logger.getLogger(medicalcompany.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null,"Cant Insert!!");
        }
    }//GEN-LAST:event_insert_bActionPerformed

    private void update_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bActionPerformed
        try{
            String sql="update mc set mc_name=?,location=? where mc_id=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,name_t.getText());
            ps.setString(2,location_t.getText());
            ps.setString(3,id_t.getText());
            int rowsUpdated=ps.executeUpdate();
            if(rowsUpdated>0){
                JOptionPane.showMessageDialog(null,"Updated successfully !");
            }
            else{
                JOptionPane.showMessageDialog(null,"No record found with the given ID");
            }
        }
        catch(SQLException ex){
            Logger.getLogger(medicalcompany.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null,"Cant update!!");
        }
            
    }//GEN-LAST:event_update_bActionPerformed

    private void delete_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bActionPerformed
        String sql = "DELETE FROM mc WHERE mc_id = ?";
        try {
            ps = con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            int rowsDeleted = ps.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(null, "Deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No record found with the given ID.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(medicalcompany.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error occurred while deleting!");
        }
    }//GEN-LAST:event_delete_bActionPerformed

    private void search_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bActionPerformed
        String sql = "SELECT * FROM mc WHERE mc_id = ?";
        try {
            ps = con.prepareStatement(sql);
            ps.setString(1, id_t.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                name_t.setText(rs.getString("mc_name"));
                location_t.setText(rs.getString("location"));
                JOptionPane.showMessageDialog(null, "Record Found");
            } else {
                JOptionPane.showMessageDialog(null, "No record found with the given ID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(medicalcompany.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error occurred while searching!");
        }
    }//GEN-LAST:event_search_bActionPerformed

    private void fac_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_bActionPerformed
        fac fac_b = new fac();
        fac_b.setVisible(true);
    }//GEN-LAST:event_fac_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_b;
    private javax.swing.JButton fac_b;
    private javax.swing.JTextField id_t;
    private javax.swing.JButton insert_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField location_t;
    private javax.swing.JTextField name_t;
    private javax.swing.JButton search_b;
    private javax.swing.JButton update_b;
    // End of variables declaration//GEN-END:variables
}
